### ISSUE TITLE
Questions about vision sensors

### ISSUE THREAD

**Issue by xspkwy** [stanfordroboticsclub/StanfordQuadruped#16]
I'm sorry I didn't find any descriptions of vision sensors in the Puppet doc. And are there any vision sensors in the Puppet?
If not, can we attach any vision sensors (or depth sensors, etc.) to the Puppet, and thus they can "see" the world?

**Comment by Nate711** [comment]
We don't have documentation on putting vision sensors on the robot but you can totally do that if you want.
